# Generated by Django 5.1.4 on 2026-07-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('pareja', 'Pareja'), ('grupal', 'Grupal'), ('premium', 'Premium')], default='individual', max_length=20)),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('capacidad_maxima', models.PositiveIntegerField(default=1)),
                ('precio_semana', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_finde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sena_tipo', models.CharField(choices=[('monto', 'Monto fijo'), ('porcentaje', 'Porcentaje del precio')], default='porcentaje', max_length=20)),
                ('sena_valor', models.DecimalField(decimal_places=2, help_text='Si es porcentaje: número de 0 a 100. Si es monto fijo: importe en pesos.', max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='circuitos/')),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, no se muestra en la web pública.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Circuito',
                'verbose_name_plural': 'Circuitos',
                'ordering': ['nombre'],
            },
        ),
    ]
