# Generated by Django 5.1.4 on 2026-07-03 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='precio_persona_adicional_finde',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por persona adicional (pasando el tramo más alto), en fin de semana/feriado.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='circuito',
            name='precio_persona_adicional_semana',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por persona adicional (pasando el tramo más alto), en día de semana.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='precio_finde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='precio_semana',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='TarifaCircuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_personas', models.PositiveIntegerField()),
                ('max_personas', models.PositiveIntegerField()),
                ('precio_persona_semana', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_persona_finde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='circuitos.circuito')),
            ],
            options={
                'verbose_name': 'Tramo de precio',
                'verbose_name_plural': 'Tramos de precio',
                'ordering': ['circuito', 'min_personas'],
                'constraints': [models.UniqueConstraint(fields=('circuito', 'min_personas', 'max_personas'), name='uniq_tramo_circuito')],
            },
        ),
    ]
