# Generated by Django 5.1.4 on 2026-07-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0002_circuito_precio_persona_adicional_finde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='capacidad_minima',
            field=models.PositiveIntegerField(default=1, help_text='Mínimo de personas para reservar este circuito (ej. Grupal: 3).'),
        ),
    ]
