# Generated by Django 5.1.4 on 2026-07-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0003_circuito_capacidad_minima'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('por_persona', models.BooleanField(default=False, help_text='Si está activo, el precio se multiplica por la cantidad indicada.')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('circuito', models.ForeignKey(blank=True, help_text='Dejar vacío para que el extra esté disponible en todos los circuitos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='circuitos.circuito')),
            ],
            options={
                'verbose_name': 'Extra / opcional',
                'verbose_name_plural': 'Extras / opcionales',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
