# Generated by Django 5.1.4 on 2026-10-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0004_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='incluye',
            field=models.TextField(blank=True, help_text='Un ítem por línea. Es la lista "¿Qué incluye?" que muestra la web.'),
        ),
    ]
