# Generated by Django 5.1.4 on 2026-07-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuitos', '0001_initial'),
        ('contactos', '0001_initial'),
        ('turnero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deseada', models.DateField()),
                ('notificado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='circuitos.circuito')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='contactos.contacto')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnero.turno')),
            ],
            options={
                'verbose_name': 'Lista de espera',
                'verbose_name_plural': 'Lista de espera',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_personas', models.PositiveIntegerField(default=1)),
                ('acompanantes', models.JSONField(blank=True, default=list, help_text='Lista de nombres de acompañantes (no son contactos independientes).')),
                ('estado', models.CharField(choices=[('pendiente_sena', 'Pendiente de seña'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('no_show', 'No-show')], default='pendiente_sena', max_length=20)),
                ('monto_sena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medio_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], max_length=20)),
                ('vencimiento_sena', models.DateTimeField(blank=True, help_text='Si vence sin pagar la seña, el cupo se libera automáticamente.', null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='circuitos.circuito')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='contactos.contacto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='turnero.turno')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha', 'turno'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], max_length=20)),
                ('tipo', models.CharField(choices=[('sena', 'Seña'), ('saldo', 'Saldo')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['circuito', 'fecha', 'turno'], name='reservas_re_circuit_e49ce0_idx'),
        ),
    ]
