# Generated by Django 5.1.4 on 2026-07-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaespera',
            name='ofrecido_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se le ofreció el lugar liberado (hold temporal antes de pasar al siguiente).', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='sena_reembolsable',
            field=models.BooleanField(blank=True, help_text='Al cancelar: True si corresponde reembolsar la seña, False si queda retenida.', null=True),
        ),
    ]
