# Generated by Django 5.1.4 on 2026-07-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_listaespera_ofrecido_at_reserva_sena_reembolsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
