# Generated by Django 5.1.4 on 2026-07-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0004_extra'),
        ('reservas', '0003_reserva_precio_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuitos.extra')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Extra de reserva',
                'verbose_name_plural': 'Extras de reserva',
                'ordering': ['created_at'],
            },
        ),
    ]
