# Generated by Django 5.1.4 on 2026-07-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reservaextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='comprobante',
            field=models.ImageField(blank=True, help_text='Comprobante de transferencia que sube el cliente por el bot.', null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='link_pago',
            field=models.URLField(blank=True, help_text='Link de pago de Mercado Pago.', max_length=500),
        ),
        migrations.AddField(
            model_name='reserva',
            name='origen',
            field=models.CharField(choices=[('manual', 'Carga manual'), ('whatsapp_bot', 'Bot de WhatsApp')], default='manual', help_text='De dónde vino la reserva (carga manual del staff o bot de WhatsApp).', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='resumen',
            field=models.TextField(blank=True, help_text='Resumen que arma el bot para mostrar en la tarjeta.'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de pago (Mercado Pago)'), ('pendiente_aprobacion', 'Pendiente de aprobación (transferencia)'), ('pendiente_sena', 'Pendiente de seña'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('no_show', 'No-show')], default='pendiente_sena', max_length=20),
        ),
    ]
