# Generated by Django 5.1.4 on 2026-08-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_comprobante_reserva_link_pago_reserva_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Clave que manda el bot para que un reintento del mismo POST no cree una reserva duplicada. Nulo en las reservas cargadas a mano.', max_length=100, null=True, unique=True),
        ),
    ]
