# Generated by Django 5.1.4 on 2026-08-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_reserva_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='sena_pagada_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se acreditó la seña. Es el punto de partida de la ventana de reembolso (config: "Horas de reembolso desde el pago"). Nulo = la seña todavía no se pagó.', null=True, verbose_name='Seña pagada el'),
        ),
    ]
