# Generated by Django 5.1.4 on 2026-07-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuitos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('recurrente_anual', models.BooleanField(default=False, help_text='Si está marcado, se repite todos los años en el mismo mes/día.')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. "Turno mañana"', max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dias_aplicables', models.JSONField(default=list, help_text='Lista de días de semana en que aplica (0=lunes ... 6=domingo). Vacío = todos los días.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BloqueoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(help_text='Ej. mantenimiento, limpieza entre turnos, feriado.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circuito', models.ForeignKey(blank=True, help_text='Vacío = bloquea todos los circuitos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='circuitos.circuito')),
                ('turno', models.ForeignKey(blank=True, help_text='Vacío = bloquea el día completo.', null=True, on_delete=django.db.models.deletion.CASCADE, to='turnero.turno')),
            ],
            options={
                'verbose_name': 'Bloqueo manual',
                'verbose_name_plural': 'Bloqueos manuales',
                'ordering': ['-fecha'],
            },
        ),
    ]
