# Generated by Django 5.1.4 on 2026-07-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriado',
            name='modo',
            field=models.CharField(choices=[('precio_finde', 'Abre con tarifa de fin de semana'), ('cerrado', 'Cerrado (no se atiende)')], default='precio_finde', help_text='"Abre con tarifa de fin de semana": ese día se atiende y se cobra el precio de finde. "Cerrado": ese día no se atiende.', max_length=20),
        ),
    ]
