# Generated by Django 5.1.4 on 2026-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0002_feriado_modo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriado',
            name='recargo_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dejalo vacío para usar el recargo general de Configuración del negocio. Completalo solo si ESTE feriado cobra un porcentaje distinto (ej. 31 de diciembre).', max_digits=5, null=True, verbose_name='Recargo propio (%)'),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='modo',
            field=models.CharField(choices=[('recargo', 'Abre con recargo sobre el precio del día'), ('cerrado', 'Cerrado (no se atiende)')], default='recargo', help_text='"Abre con recargo": se atiende y se cobra la tarifa normal del día (semana o finde, según qué día caiga) más el recargo. "Cerrado": ese día no se atiende.', max_length=20),
        ),
    ]
