# Generated by Django 5.1.4 on 2026-07-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automatizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recordatorio_24h', 'Recordatorio de turno 24h antes'), ('recordatorio_2h', 'Recordatorio de turno 2h antes'), ('reclamo_sena', 'Reclamo de seña / liberación de cupo por vencimiento'), ('encuesta_satisfaccion', 'Encuesta de satisfacción post-circuito'), ('reactivacion_inactivos', 'Reactivación de clientes inactivos'), ('alerta_cupo', 'Alerta interna de cupo completo / último lugar'), ('lista_espera', 'Oferta automática de lista de espera'), ('cumpleanos', 'Recordatorio de cumpleaños con oferta')], max_length=30, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('parametros', models.JSONField(blank=True, default=dict, help_text='Ej. {"horas_antes": 24} o {"horas_plazo_sena": 2} o {"dias_inactividad": 60}.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Automatización',
                'verbose_name_plural': 'Automatizaciones',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='AutomatizacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('error', 'Error'), ('omitido', 'Omitido')], max_length=10)),
                ('detalle', models.TextField(blank=True)),
                ('ejecutado_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de automatización',
                'verbose_name_plural': 'Logs de automatización',
                'ordering': ['-ejecutado_at'],
            },
        ),
    ]
