# Generated by Django 5.1.4 on 2026-07-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automations', '0001_initial'),
        ('contactos', '0001_initial'),
        ('reservas', '0001_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatizacion',
            name='plantilla',
            field=models.ForeignKey(blank=True, help_text='Plantilla de mensaje que usa esta automatización, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automatizaciones', to='whatsapp.plantillamensaje'),
        ),
        migrations.AddField(
            model_name='automatizacionlog',
            name='automatizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automations.automatizacion'),
        ),
        migrations.AddField(
            model_name='automatizacionlog',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contactos.contacto'),
        ),
        migrations.AddField(
            model_name='automatizacionlog',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reservas.reserva'),
        ),
    ]
