# Generated by Django 5.1.4 on 2026-07-02 20:19

import apps.vouchers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuitos', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, default=apps.vouchers.models.generar_codigo, editable=False, max_length=20, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprador_nombre', models.CharField(max_length=150)),
                ('comprador_telefono', models.CharField(blank=True, max_length=20)),
                ('comprador_email', models.EmailField(blank=True, max_length=254)),
                ('destinatario_nombre', models.CharField(blank=True, help_text='A quién se regala (opcional).', max_length=150)),
                ('mensaje_regalo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('canjeado', 'Canjeado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], db_index=True, default='activo', max_length=12)),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(help_text='Hasta cuándo se puede canjear.')),
                ('canjeado_at', models.DateTimeField(blank=True, null=True)),
                ('medio_pago', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circuito', models.ForeignKey(help_text='Circuito que regala este voucher.', on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='circuitos.circuito')),
                ('reserva_canje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Gift voucher',
                'verbose_name_plural': 'Gift vouchers',
                'ordering': ['-created_at'],
            },
        ),
    ]
