# Generated by Django 5.1.4 on 2026-08-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopupWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título grande del cartel.', max_length=120)),
                ('mensaje', models.TextField(blank=True, help_text='Texto debajo del título. Opcional si la foto ya dice todo.')),
                ('imagen', models.ImageField(blank=True, help_text='Foto o flyer de la promo. Se muestra arriba del texto. Opcional. Ojo: esta imagen es PÚBLICA (la ve cualquiera que entre a la web).', null=True, upload_to='publico/popups/')),
                ('cta_texto', models.CharField(blank=True, help_text='Ej. "Reservar por WhatsApp". Vacío = sin botón.', max_length=60, verbose_name='Texto del botón')),
                ('cta_url', models.URLField(blank=True, help_text='A dónde lleva el botón. Ej. el link de WhatsApp del spa.', max_length=500, verbose_name='Link del botón')),
                ('activo', models.BooleanField(default=False, help_text='La llave maestra: apagado, el cartel no se muestra aunque esté en fecha.')),
                ('desde', models.DateTimeField(blank=True, help_text='Vacío = desde ya. Sirve para dejar la promo cargada y que arranque sola.', null=True, verbose_name='Mostrar desde')),
                ('hasta', models.DateTimeField(blank=True, help_text='Vacío = sin fecha de fin. Pasada esta fecha deja de mostrarse solo.', null=True, verbose_name='Mostrar hasta')),
                ('repetir_horas', models.PositiveIntegerField(default=24, help_text='Si alguien lo cierra, cuántas horas esperar antes de volver a mostrárselo. 0 = mostrar siempre, en cada visita.', verbose_name='Repetir cada (horas)')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Si hay varios vigentes, se muestra el de menor orden.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popup de la web',
                'verbose_name_plural': 'Popups de la web',
                'ordering': ['orden', '-created_at'],
            },
        ),
    ]
