# Generated by Django 5.1.4 on 2026-07-02 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolution_api_url', models.CharField(blank=True, max_length=200, verbose_name='Evolution API URL')),
                ('evolution_api_key', models.CharField(blank=True, max_length=200, verbose_name='API Key')),
                ('evolution_instance_name', models.CharField(blank=True, default='crmspa', max_length=100, verbose_name='Nombre de instancia')),
                ('webhook_token', models.CharField(blank=True, help_text='Token secreto que Evolution API envía en el header al hacer webhook.', max_length=100, verbose_name='Token de webhook')),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
                'verbose_name_plural': 'Configuración WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='PlantillaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('bienvenida', 'Bienvenida'), ('confirmacion_reserva', 'Confirmación de reserva'), ('recordatorio_24h', 'Recordatorio 24h antes'), ('recordatorio_2h', 'Recordatorio 2h antes'), ('reclamo_sena', 'Reclamo de seña'), ('cancelacion', 'Cancelación'), ('encuesta', 'Encuesta de satisfacción'), ('reactivacion', 'Reactivación de inactivos'), ('cumpleanos', 'Cumpleaños'), ('lista_espera', 'Lista de espera'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('cuerpo', models.TextField(help_text='Usar {{variable}} para valores dinámicos, ej. {{nombre}}, {{circuito}}, {{fecha}}.')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Lista de nombres de variables disponibles.')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de mensaje',
                'verbose_name_plural': 'Plantillas de mensaje',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('nueva_consulta', 'Nueva consulta'), ('en_gestion', 'En gestión'), ('reserva_confirmada', 'Reserva confirmada'), ('requiere_atencion_humana', 'Requiere atención humana')], db_index=True, default='nueva_consulta', max_length=30)),
                ('bot_activo', models.BooleanField(default=True, help_text='Si está en False, n8n no debe responderle más a este contacto (handoff a un humano).', verbose_name='Bot n8n activo')),
                ('ultimo_mensaje_at', models.DateTimeField(blank=True, null=True)),
                ('mensajes_no_leidos', models.PositiveIntegerField(default=0)),
                ('archivada', models.BooleanField(db_index=True, default=False)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
                ('contacto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversacion_whatsapp', to='contactos.contacto')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-ultimo_mensaje_at'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('direccion', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('document', 'Documento'), ('audio', 'Audio'), ('video', 'Video'), ('template', 'Plantilla'), ('interactive', 'Interactivo')], default='text', max_length=20)),
                ('contenido', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=2000)),
                ('media_mime', models.CharField(blank=True, max_length=100)),
                ('media_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('error_detalle', models.TextField(blank=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_whatsapp', to='contactos.contacto')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='whatsapp.conversacion')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['timestamp'],
            },
        ),
    ]
