# Generated by Django 5.1.4 on 2026-07-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEnvioWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('request_body', models.TextField(blank=True)),
                ('response_status', models.IntegerField(null=True)),
                ('response_body', models.TextField(blank=True)),
                ('duracion_ms', models.IntegerField(null=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Log de envío WhatsApp',
                'verbose_name_plural': 'Logs de envío WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
