# Generated by Django 5.1.4 on 2026-07-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_logenviowhatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('atajo', models.CharField(help_text='Palabra clave sin barra, ej. "precios".', max_length=30, unique=True)),
                ('texto', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Respuesta rápida',
                'verbose_name_plural': 'Respuestas rápidas',
                'ordering': ['titulo'],
            },
        ),
    ]
