# Generated by Django 5.1.4 on 2026-07-03 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_contacto_fecha_nacimiento'),
        ('whatsapp', '0003_respuestarapida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mensaje',
            constraint=models.UniqueConstraint(condition=models.Q(('direccion', 'in'), models.Q(('whatsapp_message_id', ''), _negated=True)), fields=('whatsapp_message_id',), name='uniq_mensaje_entrante_wamid'),
        ),
    ]
