# Generated by Django 5.1.4 on 2026-07-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_mensaje_uniq_mensaje_entrante_wamid'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='estado_bot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
