# Generated by Django 5.1.4 on 2026-07-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_conversacion_estado_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='meta_access_token',
            field=models.CharField(blank=True, help_text='Token permanente del System User con permiso whatsapp_business_messaging.', max_length=500, verbose_name='Access Token'),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='meta_api_version',
            field=models.CharField(blank=True, default='v21.0', max_length=10, verbose_name='Versión de la Graph API'),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='meta_app_secret',
            field=models.CharField(blank=True, help_text='Para validar la firma X-Hub-Signature-256 de los webhooks.', max_length=100, verbose_name='App Secret'),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='meta_phone_number_id',
            field=models.CharField(blank=True, help_text='ID del número en Meta (WhatsApp → API Setup).', max_length=50, verbose_name='Phone Number ID'),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='meta_verify_token',
            field=models.CharField(blank=True, help_text='Token que vos elegís y cargás en Meta al configurar el webhook (verificación GET).', max_length=100, verbose_name='Verify Token'),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='meta_waba_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='WhatsApp Business Account ID'),
        ),
        migrations.AddField(
            model_name='configuracionwhatsapp',
            name='proveedor',
            field=models.CharField(choices=[('evolution', 'Evolution API (no oficial, con QR)'), ('meta', 'Meta Cloud API (oficial)')], default='evolution', help_text='Qué canal usa el CRM para enviar/recibir. Evolution conecta escaneando un QR; Meta es la API oficial (requiere número y app aprobados en Meta).', max_length=20, verbose_name='Proveedor de WhatsApp'),
        ),
    ]
