# Generated by Django 5.1.4 on 2026-07-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_configuracionwhatsapp_meta_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='media_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='media_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
