# Generated by Django 5.1.4 on 2026-07-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_mensaje_media_id_alter_mensaje_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='ventana_expira_at',
            field=models.DateTimeField(blank=True, help_text='Hasta cuándo se puede mandar texto libre por Meta (24hs desde el último mensaje entrante del cliente). Fuera de esa ventana, Meta exige plantilla.', null=True),
        ),
        migrations.AddField(
            model_name='plantillamensaje',
            name='meta_categoria',
            field=models.CharField(choices=[('utility', 'Utilidad (recordatorios, confirmaciones)'), ('marketing', 'Marketing (promociones)'), ('authentication', 'Autenticación (códigos)')], default='utility', max_length=20),
        ),
        migrations.AddField(
            model_name='plantillamensaje',
            name='meta_estado',
            field=models.CharField(blank=True, help_text='Estado de aprobación en Meta (APPROVED / PENDING / REJECTED). Se sincroniza.', max_length=20),
        ),
        migrations.AddField(
            model_name='plantillamensaje',
            name='meta_idioma',
            field=models.CharField(default='es_AR', help_text='Código de idioma de la plantilla en Meta (ej. es_AR, es, en_US).', max_length=10),
        ),
        migrations.AddField(
            model_name='plantillamensaje',
            name='meta_nombre',
            field=models.CharField(blank=True, help_text='Nombre EXACTO de la plantilla aprobada en Meta (minúsculas y guiones bajos). Si se deja vacío, se usa el "nombre" normalizado.', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantillamensaje',
            name='cuerpo',
            field=models.TextField(help_text='Usar {{variable}} para valores dinámicos, ej. {{nombre}}, {{circuito}}, {{fecha}}. Para plantillas de Meta usar posicionales: {{1}}, {{2}}.'),
        ),
    ]
