# Generated by Django 5.1.4 on 2026-07-02 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0003_contacto_fecha_nacimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('whatsapp', 'WhatsApp'), ('preparacion', 'Preparación de sala'), ('seguimiento', 'Seguimiento'), ('otro', 'Otro')], default='seguimiento', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_programada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('vencida', 'Vencida')], db_index=True, default='pendiente', max_length=20)),
                ('resultado', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to=settings.AUTH_USER_MODEL)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='contactos.contacto')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['fecha_programada'],
            },
        ),
    ]
