# Generated by Django 5.1.4 on 2026-07-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='Spa de Campo', max_length=150)),
                ('dias_laborables', models.JSONField(blank=True, default=list, help_text='Días de semana en que el negocio atiende (0=lunes ... 6=domingo). Vacío = todos.')),
                ('horario_atencion_desde', models.TimeField(blank=True, null=True)),
                ('horario_atencion_hasta', models.TimeField(blank=True, null=True)),
                ('plazo_pago_sena_horas', models.PositiveIntegerField(default=2, help_text='Horas para pagar la seña antes de liberar el cupo automáticamente.')),
                ('politica_cancelacion', models.TextField(blank=True, help_text='Ej. "Reembolso de seña hasta 24h antes del turno."')),
                ('horas_cancelacion_con_reembolso', models.PositiveIntegerField(default=24, help_text='Horas de anticipación para cancelar con reembolso de seña.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del negocio',
                'verbose_name_plural': 'Configuración del negocio',
            },
        ),
    ]
