# Generated by Django 5.1.4 on 2026-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='reserva_exclusiva_por_turno',
            field=models.BooleanField(default=True, help_text='Si está activo, cada turno (mañana/tarde) admite UNA sola reserva en todo el spa, sin importar el circuito: quien contrata no comparte el turno con otros clientes. El tamaño del grupo se limita a la capacidad del circuito. Si se desactiva, cada circuito lleva su propio cupo por separado.', verbose_name='Reserva exclusiva por turno'),
        ),
    ]
