# Generated by Django 5.1.4 on 2026-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configuracionnegocio_reserva_exclusiva_por_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='dias_tarifa_finde',
            field=models.JSONField(blank=True, default=list, help_text='Días de la semana que cobran tarifa de fin de semana (0=lunes … 6=domingo). Vacío = sábado y domingo. En este spa: viernes, sábado y domingo → [4, 5, 6].'),
        ),
    ]
