# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_configuracionnegocio_dias_tarifa_finde'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='email_notificaciones',
            field=models.CharField(blank=True, help_text='Uno o varios emails separados por coma. Reciben un aviso cuando: el bot crea una reserva, se confirma una reserva, se cancela una reserva, o una conversación pasa a requerir atención humana. Vacío = no se manda nada.', max_length=500, verbose_name='Email de notificaciones'),
        ),
    ]
