# Generated by Django 5.1.4 on 2026-08-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    """Cambia la política de reembolso de la seña.

    `horas_cancelacion_con_reembolso` medía horas de anticipación **al turno**;
    `horas_reembolso_desde_pago` mide horas **desde el pago de la seña**. Como el punto de
    referencia es otro, el valor viejo no se migra: arrastrarlo sería aplicar un número pensado
    para otra cuenta. El campo nuevo arranca en el default de la política (24 hs).
    """


    dependencies = [
        ('configuracion', '0004_configuracionnegocio_email_notificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionnegocio',
            name='horas_cancelacion_con_reembolso',
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='horas_reembolso_desde_pago',
            field=models.PositiveIntegerField(default=24, help_text='La seña se reembolsa SOLO si la reserva se cancela dentro de esta cantidad de horas contadas DESDE EL PAGO de la seña (no desde la fecha del turno). Pasado ese plazo, la seña queda retenida. Default: 24.', verbose_name='Horas de reembolso desde el pago'),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='politica_cancelacion',
            field=models.TextField(blank=True, help_text='Texto de la política que se le muestra al cliente. Ej. "La seña se reembolsa solo si cancelás dentro de las 24 hs posteriores al pago."'),
        ),
    ]
