# Generated by Django 5.1.4 on 2026-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_remove_configuracionnegocio_horas_cancelacion_con_reembolso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='recargo_feriado_porcentaje',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Porcentaje que se suma al precio del día cuando la fecha es feriado. Se aplica SOBRE la tarifa que ya le corresponde a ese día: si el feriado cae un sábado, es precio de finde + este %; si cae un día de semana, es precio de semana + este %. Un feriado puntual puede llevar su propio porcentaje distinto (Configuración → Feriados).', max_digits=5, verbose_name='Recargo por feriado (%)'),
        ),
    ]
