# Generated by Django 5.1.4 on 2026-09-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_configuracionnegocio_recargo_feriado_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnegocio',
            name='como_llegar',
            field=models.TextField(blank=True, help_text='Referencias prácticas del acceso: por dónde entrar, estado del camino, qué mirar. Ej. "Los últimos metros son camino de tierra: si llovió, vení con tiempo". Evita llamados y llegadas tarde.', verbose_name='Cómo llegar (referencias)'),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección tal cual querés que la lea el cliente. Podés dejarla vacía y usar solo el link del mapa.', max_length=250),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='mapa_url',
            field=models.URLField(blank=True, help_text='Link de Google Maps al spa. Es lo que le llega al cliente para llegar: toca y le abre el GPS.', max_length=500, verbose_name='Link del mapa'),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='url_politicas',
            field=models.URLField(blank=True, help_text='Página de políticas de reserva y cancelación. Se incluye en la confirmación para que el cliente las tenga a mano desde el principio.', max_length=500, verbose_name='Link a las políticas'),
        ),
    ]
