# Generated by Django 5.1.4 on 2026-07-02 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuitos', '0001_initial'),
        ('contactos', '0003_contacto_fecha_nacimiento'),
        ('whatsapp', '0002_logenviowhatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('modo_seleccion', models.CharField(choices=[('segmento', 'Por segmento (filtros automáticos)'), ('manual', 'Selección manual de contactos')], default='segmento', max_length=10)),
                ('filtro_dias_inactividad', models.PositiveIntegerField(blank=True, help_text='Solo contactos sin reservas en los últimos N días.', null=True)),
                ('contactos_ids', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('en_ejecucion', 'En ejecución'), ('completada', 'Completada')], default='borrador', max_length=20)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('total_destinatarios', models.PositiveIntegerField(default=0)),
                ('enviados', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('filtro_circuito', models.ForeignKey(blank=True, help_text='Solo contactos que alguna vez reservaron este circuito.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='circuitos.circuito')),
                ('filtro_etiquetas', models.ManyToManyField(blank=True, related_name='campanas', to='contactos.etiqueta')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanas', to='whatsapp.plantillamensaje')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvioCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=10)),
                ('detalle', models.TextField(blank=True)),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='campanas.campana')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contactos.contacto')),
            ],
            options={
                'verbose_name': 'Envío de campaña',
                'verbose_name_plural': 'Envíos de campaña',
                'ordering': ['-enviado_at'],
            },
        ),
    ]
