# Generated by Django 5.1.4 on 2026-07-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanas', '0002_registrar_beat'),
        ('contactos', '0004_campopersonalizado_contacto_datos_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='filtro_campo',
            field=models.ForeignKey(blank=True, help_text='Filtrar por un campo personalizado del contacto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactos.campopersonalizado'),
        ),
        migrations.AddField(
            model_name='campana',
            name='filtro_campo_operador',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='campana',
            name='filtro_campo_valor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='campana',
            name='filtro_con_email',
            field=models.BooleanField(default=False, help_text='Solo contactos que tienen email cargado.'),
        ),
        migrations.AddField(
            model_name='campana',
            name='filtro_min_reservas',
            field=models.PositiveIntegerField(blank=True, help_text='Solo contactos con al menos N reservas (clientes frecuentes).', null=True),
        ),
    ]
