# Generated by Django 5.1.4 on 2026-07-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
