# Generated by Django 5.1.4 on 2026-07-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_contacto_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('fecha', 'Fecha'), ('booleano', 'Sí / No'), ('lista', 'Lista de opciones')], default='texto', max_length=20)),
                ('opciones', models.JSONField(blank=True, default=list, help_text='Para tipo "Lista": una opción por línea.')),
                ('requerido', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campo personalizado',
                'verbose_name_plural': 'Campos personalizados',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Valores de los campos personalizados, indexados por slug.'),
        ),
    ]
