# Generated by Django 5.1.4 on 2026-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0004_campopersonalizado_contacto_datos_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='recibir_promociones',
            field=models.BooleanField(default=True, help_text='Reactivación, cumpleaños y campañas de difusión.', verbose_name='Recibir promociones'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='recibir_recordatorios',
            field=models.BooleanField(default=True, help_text='Recordatorios de turno, aviso de seña y ofertas de lista de espera.', verbose_name='Recibir recordatorios'),
        ),
    ]
