# Generated by Django 5.1.4 on 2026-07-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0005_contacto_recibir_promociones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='archivos',
            field=models.JSONField(blank=True, default=list, help_text='Fotos, audios y documentos intercambiados por WhatsApp con este contacto.'),
        ),
    ]
